### ISSUE TITLE
`__WCHAR_TYPE__` unsupported 

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#32] opened 2021-03-11 22:15 UTC
#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
wchar.c:0:0 warning: missing type specifier, assume `int'wchar.c:0:15 error: expected `,' or `;' or `=' after declarator, got `wchar_t'
__WCHAR_TYPE__ wchar_t;
               ^

(return code 0)
```

#### Content of file
```bash
__WCHAR_TYPE__ wchar_t;
```

#### `psychec` version
```bash
commit d10dc1ddfb7ea845f59274a4d6ca5d021ab31423
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Mar 9 21:18:30 2021 -0300

    fix postfixing on compound literal
```

**Comment by andrewvaughanj** [comment] 2021-03-11 22:16
The output *is not* a copy-and-paste error; the message genuinely comes out mangled like that!

**Comment by ltcmelo** [comment] 2022-01-21 14:28
Closing this issue as it is in reality a duplicate of issue #35 , __WCHAR_TYPE__ is [predefined macro](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html#Common-Predefined-Macros)
from the same "group" as __UINT32_TYPE__.

**Closed by ltcmelo** 2022-01-21 14:28 UTC
Labels: bug, duplicate, parser
