### ISSUE TITLE
psychecsolver-exe: user error (Cannot unify types with different constructors: char void)

### ISSUE THREAD

**Issue by stoneThunder43** [ltcmelo/psychec#74] opened 2022-02-18 15:59 UTC
Hi, thanks for this really interesting project.

I am interested in the type inference offered by psyche-c. I see this is only available in the "original" branch of the project at the moment. 

I have successfully built all components on this branch and I have been able to use cnip.sh to compile some simple examples, like the one given in the readme.

However, when I try to use cnip.sh on more complex examples I nearly always receive this:
```
psychecsolver-exe: user error (Cannot unify types with different constructors:
char and void)
```
(sometimes with different types e.g. bool or int)

I looked at some of the examples in the accompanying research paper and I attempted to get cnip.sh to work with them. For example, I tried to compile `basename.c` from the GNU Coreutils project (version 8.27) after commenting out the includes and top level declarations. However, this resulted in the same error.

I read that macros can also cause issues, so included the correct definitions for the macros identified in the research paper as causing syntax errors. Despite this I'm still unable to compile the code.

I have attached the code I am attempting to use cnip.sh with as an example.
[basename.c.txt](https://github.com/ltcmelo/psychec/files/8098492/basename.c.txt)
[macros.h.txt](https://github.com/ltcmelo/psychec/files/8098509/macros.h.txt)

Is this due to limitations of psyche-c or am I doing something wrong? 

**Version**

The "original" branch.

**Expected behavior**
cnip.sh is able to compile the attached basename.c file (with or without the macros.h).

Thanks!

**Comment by ltcmelo** [comment] 2022-02-18 16:38
> thanks for this really interesting project.

Thank you  @stoneThunder43 ! I'm glad that you liked it 👍🏽 

_cnip.sh_ is wrapper around Psyche-C's type inference together with extra functionality. For instance, it attempts to match names from stdlib's headers and to account for common type synonyms. But it never got robust enough and in many cases it introduces preprocessed text that causes error.

The best way to try out Psyche-C's type inference is by invoking the constraint generator and solver explicitly. I'm attaching a [python script](https://github.com/ltcmelo/psychec/files/8098732/reconstruct.py.txt) that does exactly that (this script used to be in the source code tree but I must have removed it at some point).

In regards to your GNU coreutils tests, it still is necessary to remove the `#include`s. I just removed those from your _basename.c.txt_ and it works (there are still warnings but those are in the paper too).

<img width="508" alt="Screen Shot 2022-02-18 at 13 36 07" src="https://user-images.githubusercontent.com/2905588/154724256-1afaa93f-e403-4ac0-85f0-eeb2b084ba09.png">

That said, you might of course bump into genuine bugs of the type inference itself (rather than those caused by _cnip.sh_) but I won't be fixing them in the original branch given that a new type inference is under construction. So I'm closing this report.

**Closed by ltcmelo** 2022-02-18 16:38 UTC
Labels: bug
