### ISSUE TITLE
Pre-ANSI declarations not supported (but are supported by clang/gcc in `-std=c11`)

### ISSUE THREAD

**Issue by andrewvaughanj** [ltcmelo/psychec#11] opened 2021-02-23 13:18 UTC
**If eligible for the bounty, I wish this to be donated to a local animal charity of the maintainer's choice**

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `clang -Werror -Wall -Wextra -Wpedantic -pedantic -std=c11 -c $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
930506-1.c:2:10 error: expected , or `;' or = after declarator, got `double'
long f(a) double a;
          ^
930506-1.c:2:20 warning: missing type specifier, assume `int'
long f(a) double a;
                    ^
930506-1.c:2:20 error: expected <identifier> or `(' starting direct-declarator, got `{'
long f(a) double a;
                    ^
930506-1.c:3:12 warning: missing type specifier, assume `int'
{ return a; }
            ^
930506-1.c:3:12 error: expected <identifier> or `(' starting direct-declarator, got `}'
{ return a; }
            ^

(return code 0)
```

#### Content of file
```bash
long f(a) double a;
{ return a; }
```

#### `psychec` version
```bash
commit 6d7b8249e0f28af105112b217cb33a24f666e148
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 07:47:25 2021 -0300

    link expression-parsing table in Doxygen documentation
```

**Comment by andrewvaughanj** [comment] 2021-02-23 13:19
Another example:

#### GCC version:
```bash
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
```

#### clang version:
```bash
clang version 11.0.1
```

#### Output of `gcc -c -Wall -Wextra -Wpedantic -Werror -std=c11 $FNAME`
```bash
(return code 0)
```

#### Output of `clang -c -Wall -Wextra -Wpedantic -Werror -std=c11 $FNAME`
```bash
(return code 0)
```

#### Output of `cnip $FNAME`
```bash
mword1.c:2:14 error: expected , or `;' or = after declarator, got `int'
int foo(a, b) int *a, *b;
              ^
mword1.c:2:26 warning: missing type specifier, assume `int'
int foo(a, b) int *a, *b;
                          ^
mword1.c:2:26 error: expected <identifier> or `(' starting direct-declarator, got `{'
int foo(a, b) int *a, *b;
                          ^
mword1.c:5:2 warning: missing type specifier, assume `int'
  return 0;
  ^
mword1.c:5:2 error: expected <identifier> or `(' starting direct-declarator, got `return'
  return 0;
  ^
mword1.c:5:12 warning: missing type specifier, assume `int'
  return 0;
            ^
mword1.c:5:12 error: expected <identifier> or `(' starting direct-declarator, got `}'
  return 0;
            ^

(return code 0)
```

#### Content of file
```bash
int foo(a, b) int *a, *b;
{
  *a = *b;
  return 0;
}
```

#### `psychec` version
```bash
commit 6d7b8249e0f28af105112b217cb33a24f666e148
Author: Leandro T. C. Melo <LTCMELO@GMAIL.COM>
Date:   Tue Feb 23 07:47:25 2021 -0300

    link expression-parsing table in Doxygen documentation


```

**Comment by ltcmelo** [comment] 2021-02-23 17:13
Thank you again, @andrewvaughanj . This one is a duplicate of #6 , though — but it isn't immediate to notice, since the other bug is reported with another title.

**Comment by andrewvaughanj** [comment] 2021-02-23 17:22
Doh 🤦 I'd missed that was reason for the duffs device one failing!

Do you want me to close this?

**Comment by ltcmelo** [comment] 2021-02-23 19:59
Yes, I guess this can be closed.

**Closed by ltcmelo** 2021-02-23 19:59 UTC
Labels: bug, duplicate, parser, verified

**Comment by ltcmelo** [comment] 2021-02-23 20:01
@andrewvaughanj I also amended the title of the other bug so it'll be easier for others to spot.
